modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL v3"
issueTrackerURL = "https://github.com/Noxcrew/noxesium/issues"

[[mods]]
modId = "noxesium"
version = "${version}"
displayName = "Noxesium"
authors = "Noxcrew"
logoFile = "logo-neoforge.png"
description = '''
Improves play experience on large multiplayer servers.
'''

[[mixins]]
config = "noxesium-common.mixins.json"

[[mixins]]
config = "noxesium-sodium.mixins.json"

[[mixins]]
config = "noxesium-forge.mixins.json"

[[dependencies.noxesium]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.4,]"

[[dependencies.noxesium]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.4.0-beta,]"

[[dependencies.noxesium]]
    modId = "optifine"
    type = "incompatible"
    reason = "OptiFine makes changes to the game that make development of Noxesium much harder. Please uninstall Noxesium if you want to use OptiFine."