name: NoxesiumApi
version: 1.0.0
main: com.noxcrew.noxesium.paper.NoxesiumPaper
api-version: 1.16
commands:
    noxlist:
        description: See a list of users that have Noxesium installed.
        usage: /noxlist
        permission: noxesium.noxlist